# Generated by Django 4.2.4 on 2023-08-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='products.wishlist'),
        ),
    ]
