# Generated by Django 4.2.4 on 2023-08-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(related_name='products', to='products.wishlist'),
        ),
    ]
